# Generated by Django 4.2.11 on 2026-05-28 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("event_code", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("end_date", models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
