# Generated by Django 6.0.2 on 2026-02-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('attendee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_one', to='attendees.attendee')),
                ('attendee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_two', to='attendees.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('event', 'attendee1', 'attendee2')},
            },
        ),
    ]
